### ISSUE TITLE
No language specific subtyping?

### ISSUE THREAD

**Issue by yoavg** [UniversalDependencies/tools#17]
We get a `validate.py` errors complaining about various relations. I thought these were allowed?

**Comment by yoavg** [comment]
Some examples:
```
[Line                   33]: Unknown UD DEPREL: obl:tmod
[Line                   39]: Unknown UD DEPREL: compound:smixut
[Line                   55]: Unknown UD DEPREL: compound:smixut
[Line                   56]: Unknown UD DEPREL: compound:smixut
[Line                   65]: Unknown UD DEPREL: compound:smixut
[Line                   69]: Unknown UD DEPREL: flat:name
```

**Comment by dan-zeman** [comment]
They must be permitted explicitly and separately for each treebank, even if they are mentioned in the universal part of the documentation. I just added `flat:name` and replaced former `nmod:tmod` by `obl:tmod`. I also replaced `nmod:smixut` by `compound:smixut` but I do not know whether the new relation is really a replacement of the old one, or whether both should be allowed now.

**Comment by dan-zeman** [comment]
Hebrew passes validation now, so I am closing this issue.

**Comment by rtsarfaty** [comment]
We FAIL validation on Hebrew now due to nmod:tmod relations.
This happens in case we have a copular sentence with a temporal modifying the predicate, which happens to be the noun.

An example would be:

"The topic yesterday was immigration"

where "yesterday" intends to indicate the tense of the sentence and thus it is attached as a dependent of "immigration", and since it becomes a modifying element of a noun it is tagged nmod:tmod. 

Is this relation not allowed in principle, or should it simply be added explicitly like the others?

@yoavg @dan-zeman

**Comment by dan-zeman** [comment]
If yesterday is analyzed as modifying the clause, then I believe UD v2 expects it to be `obl` (and since you have a language-specific extension, it would be `obl:tmod`). You could in theory have `nmod:tmod` (or you could use normal `nmod` here) but that would be saying that _yesterday_ is an attribute of the noun _immigration_, not of the clause. That is, there is a concept of _immigration yesterday_ (as opposed to immigration on any other day), and this special kind of immigration was the topic of some discussion (which may have taken place today morning or who knows when).

**Comment by ftyers** [comment]
Shouldn't [was immigration] be treated as a clause ? And so should get `obl:tmod` (if 'yesterday' is a nominal) or `advmod` (if it is an adverbial) ?

**Comment by rtsarfaty** [comment]
the idea is that it modifies the predicative clause, but since the predicate in these particular sentences  (6 in total) headed by a noun it creates the impression that there is a dependence on a NOUN rather than on a clausal element (the cop element is of course dependent on this noun).

I am totally fine with obl:tmod, will apply if there are no objections.

**Comment by rtsarfaty** [comment]
another related issue:

in our language specific subtypes we have obl:poss
which results from the construction:

[construct-state] >possessive> NOUN >case:gen> ADP

the problem here seems to be of a more general type:
when [construct state] is headed by a noun the "possessive" is "nmod:poss", which is good.
when [construct state] is headed by something else (e.g., JJ) there is a fallback to "obl:poss", which is the only "valid" case in the matrix describing the dep relations.

I argue that this is not a satisfactory solution, because [construct-state] there are no non-core arguments here. In fact, even it the construct state consists of no noun, it is, in the end, a sort of a nominal inside nmod:poss relation.

The most suitable relation here becomes compound:poss, and this is what we apply for now, in the hope that this will pass validation -- unless anyone has a better suggestion.

@yoavg @dan-zeman

**Comment by jnivre** [comment]
Why can't you just do nmod:poss also in the adjective case? I realize this is not the same case, but we do it in Swedish for NPs where the head noun is missing and the adjective gets promoted:

ge mig den blå boken på bordet och den röda på golvet
give me the blue book <-nmod- [on table-DEF] and the red <-nmod- [on floor-DEF]

**Comment by jnivre** [comment]
The important thing is not what the part-of-speech tag of the word is, but whether it functions as a predicate or as a nominal.

**Comment by dan-zeman** [comment]
I don't find `obl:poss` satisfactory either. I would probably go just with `nmod:poss`.

Note that it will pass validation if the part before the colon is a universal relation and if you add it to the `deprel.he` file in tools. This is not to say that you should put anything there without giving it a thought :-)

**Comment by rtsarfaty** [comment]
thanks, nmod:poss is good for us if it is allowed to hang on a non-noun head. we will push the fix.

it also means hebrew will pass validation without extending the lang-spec relations, which I think is a good thing.

**Comment by rtsarfaty** [comment]
hebrew passes validation now, so I am closing this.
