### ISSUE TITLE
Add a "goeswith" exception to some validation rules

### ISSUE THREAD

**Issue by bguil** [UniversalDependencies/tools#39]
The current validator emits a warning if the dependent of an `advmod` relation is different from all the UPOS: `ADV`, `ADJ`, `CCONJ`, `PART` and `SYM` except if the dependent is in a `fixed` construction.
I propose to add the same exception if the dependant is in a `goeswith` construction.

Some examples of invalid annotations that would become valid with this proposition:
 * 3 examples in [UD_English-GUM](http://match.grew.fr/?corpus=UD_English-GUM@2.3&custom=5c793e12a5fc5)
 * 3 examples in [UD_French-GSD](http://match.grew.fr/?corpus=UD_French-GSD@2.3&custom=5c793e12a5fc5)

**Comment by dan-zeman** [comment]
If there is a `fixed` dependent, the current word is the first word of a fixed expression and the current word's part of speech may differ from the POS category that the entire expression matches.

I think the situation with `goeswith` is different. An adverb was mistakenly split by a space character. The individual parts do not have their own POS category. My assumption was that they would still be tagged `ADV` (although, perhaps we should consider `X` as a possibility, too). If _beforehand_ is split to two parts and then connected using `goeswith`, there is in principle no difference where the split occurs: _before hand_, _be forehand_ and _bef orehand_ should all be treated the same, i.e. _before_ should not be `ADP` and _be_ should not be `AUX` just because they look like some other words.

**Comment by amir-zeldes** [comment]
I understand the reasoning behind what @dan-zeman is saying, and for cases like bef + orehand it's easy to understand, but for before + hand, this would produce some unexpected results for users taking naive word/lemma + POS stats, as they would discover that before and hand can both be adverbs... In this case in particular, the writer is using a historically motivated (if synchronically incorrect) orthography, so it's unclear to me that it's an improvement to change the informative tag ADP to the less informative one ADV.

**Comment by dan-zeman** [comment]
Okay, fair enough. I'll put the exception in the validator and leave it up to the annotators to decide what the best tags are in a `goeswith` expression.

**Comment by dan-zeman** [comment]
Fixed in https://github.com/UniversalDependencies/tools/commit/80fa36fe596a1bce851e10e6281c44b8553ecd2a.
